In [2]:
    ''''
        Shark Attack Project
      
    Instead of ignoring the problem or pretending that we can put up nets and 
    protect everyone from sharks, what is needed is a public education campaign
    to teach people how to co-exist with sharks Lewis Levine, M.D.
    '''
    
    '''
    FATAL SHARK BY YEAR
    '''

"'\n    Shark Attack Project\n  \nInstead of ignoring the problem or pretending that we can put up nets and \nprotect everyone from sharks, what is needed is a public education campaign\nto teach people how to co-exist with sharks Lewis Levine, M.D.\n"

# Opening the file:

In [3]:
import pandas as pd
import numpy as np

In [4]:
sattack = pd.read_csv('attacks.csv.zip',compression='zip',encoding='latin1')

sattack.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [4]:
sattack.head(3)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN

In [157]:
sattack.info

<bound method DataFrame.info of        case number         date    year        Type             Country  \
0       2018.06.25  25-Jun-2018  2018.0     Boating                 USA
1       2018.06.18  18-Jun-2018  2018.0  Unprovoked                 USA
2       2018.06.09  09-Jun-2018  2018.0     Invalid                 USA
6     2018.06.03.a  03-Jun-2018  2018.0  Unprovoked              BRAZIL
7       2018.05.27  27-May-2018  2018.0  Unprovoked                 USA
...            ...          ...     ...         ...                 ...
6243       ND.0063        1960s     0.0  Unprovoked                IRAQ
6254       ND.0051  Before 1957     0.0    Provoked                CUBA
6265       ND.0038    1941-1942     0.0  Unprovoked                IRAQ
6276       ND.0026  Early 1930s     0.0  Unprovoked              BELIZE
6301       ND.0001    1845-1853     0.0  Unprovoked  CEYLON (SRI LANKA)

                  Area                                           Location  \
0           California                        Oceanside, San Diego County
1              Georgia                     St. Simon Island, Glynn County
2               Hawaii                                       Habush, Oahu
6           Pernambuco                              Piedade Beach, Recife
7              Florida  Lighhouse Point Park, Ponce Inlet, Volusia County
...                ...                                                ...
6243            Basrah             Shatt-al-Arab River near Abu al Khasib
6254   Havana Province                                            Cojimar
6265            Basrah        Shatt-el Arab River near a small boat stand
6276               NaN                                                NaN
6301  Eastern Province                Below the English fort, Trincomalee

                                               Activity  \
0                                              Paddling
1                                              Standing
2                                               Surfing
6                                              Swimming
7                                               Fishing
...                                                 ...
6243  Swimming in section of river used for washing ...
6254                   Shark fishing, knocked overboard
6265                                           Swimming
6276                                           Standing
6301                                           Swimming

                        Name Sex   ...         Species   \
0                Julie Wolfe    F  ...      White shark
1            Adyson McNeely     F  ...              NaN
2                John Denges    N  ...              NaN
6     Jose Ernesto da Silva     N  ...      Tiger shark
7                       male    N  ...  Lemon shark, 3'
...                      ...  ...  ...              ...
6243                    male    N  ...       Bull shark
6254              Sandrillio    N  ...              NaN
6265                    male    N  ...       Bull shark
6276               a servant    N  ...  12' tiger shark
6301                    male    N  ...              NaN

               Investigator or Source                        pdf  \
0                    R. Collier, GSAF       2018.06.25-Wolfe.pdf
1      K.McMurray, TrackingSharks.com     2018.06.18-McNeely.pdf
2      K.McMurray, TrackingSharks.com      2018.06.09-Denges.pdf
6      Diario de Pernambuco, 6/4/2018   2018.06.03.a-daSilva.pdf
7     K. McMurray, TrackingSharks.com       2018.05.27-Ponce.pdf
...                               ...                        ...
6243     B.W. Coad & L.A.J. Al-Hassan  ND-0063-Shatt-al-Arab.pdf
6254            F. Poli, pp.75, 81-83     ND-0051-Sandrillio.pdf
6265     B.W. Coad & L.A.J. Al-Hassan  ND-0038-Shatt-al-Arab.pdf
6276                  Mitchell-Hedges         ND-0026-Belize.pdf
6301                       S.W. Baker         ND-0001-Ceylon.pdf

                                           href formula  \
0     http://sharkattackfile.net/spreadsheets/pdf_di...
1     http://sharkattackfile.net/spreadsheets/pdf_di...
2     http://sharkattackfile.net/spreadsheets/pdf_di...
6     http://sharkattackfile.net/spreadsheets/pdf_di...
7     http://sharkattackfile.net/spreadsheets/pdf_di...
...                                                 ...
6243  http://sharkattackfile.net/spreadsheets/pdf_di...
6254  http://sharkattackfile.net/spreadsheets/pdf_di...
6265  http://sharkattackfile.net/spreadsheets/pdf_di...
6276  http://sharkattackfile.net/spreadsheets/pdf_di...
6301  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number.1  \
0     http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.25
1     http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.18
2     http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.09
6     http://sharkattackfile.net/spreadsheets/pdf_di...  2018.06.03.a
7     http://sharkattackfile.net/spreadsheets/pdf_di...    2018.05.27
...                                                 ...           ...
6243  http://sharkattackfile.net/spreadsheets/pdf_di...       ND.0063
6254  http://sharkattackfile.net/spreadsheets/pdf_di...       ND.0051
6265  http://sharkattackfile.net/spreadsheets/pdf_di...       ND.0038
6276  http://sharkattackfile.net/spreadsheets/pdf_di...       ND.0026
6301  http://sharkattackfile.net/spreadsheets/pdf_di...       ND.0001

     Case Number.2 original order Unnamed: 22 Unnamed: 23
0       2018.06.25         6303.0         NaN         NaN
1       2018.06.18         6302.0         NaN         NaN
2       2018.06.09         6301.0         NaN         NaN
6     2018.06.03.a         6297.0         NaN         NaN
7       2018.05.27         6296.0         NaN         NaN
...            ...            ...         ...         ...
6243       ND.0063           60.0         NaN         NaN
6254       ND.0051           49.0         NaN         NaN
6265       ND.0038           38.0         NaN         NaN
6276       ND.0026           27.0         NaN         NaN
6301       ND.0001            2.0         NaN         NaN

[3465 rows x 24 columns]>

In [5]:
sattack.describe()

              Year  original order
count  6300.000000     6309.000000
mean   1927.272381     3155.999683
std     281.116308     1821.396206
min       0.000000        2.000000
25%    1942.000000     1579.000000
50%    1977.000000     3156.000000
75%    2005.000000     4733.000000
max    2018.000000     6310.000000

In [5]:
sattacksub = sattack

In [6]:
sattacksub.isnull()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25719,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25720,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25721,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25722,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [47]:
sattacksub.dropna(how='all',)

,case number,date,year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
sattacksub.head(10)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,N,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,N,...,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,N,...,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,N,...,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0,NaN,NaN
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,N,...,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294.0,NaN,NaN
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,N,...,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0,NaN,NaN
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,N,...,NaN,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.21,2018.05.21,6292.0,NaN,NaN
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,N,...,NaN,"C. Creswell, GSAF & K. McMurray TrackingSharks...",2018.05.13.b-Turrell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.b,2018.05.13.b,6291.0,NaN,NaN

In [61]:
sattacksub.drop(columns='Unnamed: 22')

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,N,...,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,N,...,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,N,...,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6243,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,N,...,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0,NaN
6254,ND.0051,Before 1957,0.0,Provoked,CUBA,Havana Province,Cojimar,"Shark fishing, knocked overboard",Sandrillio,N,...,NaN,NaN,"F. Poli, pp.75, 81-83",ND-0051-Sandrillio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0051,ND.0051,49.0,NaN
6265,ND.0038,1941-1942,0.0,Unprovoked,IRAQ,Basrah,Shatt-el Arab River near a small boat stand,Swimming,male,N,...,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0038-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0038,ND.0038,38.0,NaN
6276,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,N,...,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0,NaN
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,N,...,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN

In [63]:
sattacksub.isna().sum()

Case Number                  0
Date                         0
Year                         1
Type                         0
Country                      9
Area                       118
Location                   150
Activity                   141
Name                        11
Sex                         38
Age                          0
Injury                       4
Fatal (Y/N)                225
Time                      1111
Species                   1276
Investigator or Source       0
pdf                          0
href formula                 1
href                         0
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               3464
Unnamed: 23               3465
dtype: int64

In [6]:
sattack.dropna(how='all')

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
sattack.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [1]:
sattack.loc[:,'Species ']

NameError: name 'sattack' is not defined

In [8]:
nan_value = float('NaN')

In [9]:
sattack.replace("",nan_value,inplace=True)

In [10]:
sattack.dropna(subset=['Investigator or Source'],inplace=True)

In [11]:
sattack.dropna(subset=['Age'],inplace=True)

In [14]:
dictattack = dict(sattack.loc[:,'Year'].value_counts())

dictattack

{2015.0: 116,
 2016.0: 99,
 2012.0: 97,
 2011.0: 96,
 2013.0: 95,
 2008.0: 90,
 2017.0: 90,
 2007.0: 84,
 2014.0: 82,
 2009.0: 82,
 2006.0: 80,
 2002.0: 79,
 2005.0: 76,
 2010.0: 73,
 2003.0: 71,
 2000.0: 69,
 2001.0: 67,
 2004.0: 64,
 1995.0: 54,
 1999.0: 51,
 1962.0: 49,
 1998.0: 49,
 1961.0: 46,
 1959.0: 46,
 1960.0: 45,
 1997.0: 44,
 1966.0: 43,
 1996.0: 41,
 2018.0: 39,
 1964.0: 39,
 1963.0: 38,
 1993.0: 36,
 1975.0: 35,
 1989.0: 35,
 1988.0: 35,
 1983.0: 33,
 1992.0: 33,
 1994.0: 33,
 1968.0: 32,
 1967.0: 32,
 1958.0: 29,
 1974.0: 29,
 1965.0: 29,
 1991.0: 28,
 1990.0: 27,
 1956.0: 27,
 1981.0: 27,
 1982.0: 27,
 1984.0: 26,
 1986.0: 24,
 1970.0: 24,
 1985.0: 23,
 1971.0: 23,
 1951.0: 22,
 1980.0: 21,
 1972.0: 21,
 1987.0: 21,
 1957.0: 20,
 1969.0: 20,
 1947.0: 19,
 1954.0: 19,
 1950.0: 19,
 1976.0: 19,
 1946.0: 18,
 1955.0: 18,
 1949.0: 17,
 1973.0: 16,
 1977.0: 16,
 1948.0: 15,
 1979.0: 15,
 1929.0: 14,
 1935.0: 14,
 1953.0: 14,
 1934.0: 14,
 0.0: 13,
 1978.0: 13,
 1937.0: 13,
 1944.0: 13,
 1942.0: 11,
 1916.0: 10,
 1922.0: 10,
 1930.0: 10,
 1936.0: 10,
 1952.0: 10,
 1940.0: 10,
 1941.0: 9,
 1938.0: 9,
 1939.0: 8,
 1928.0: 8,
 1931.0: 8,
 1943.0: 8,
 1924.0: 8,
 1932.0: 7,
 1905.0: 7,
 1870.0: 6,
 1920.0: 6,
 1880.0: 5,
 1945.0: 5,
 1899.0: 5,
 1921.0: 5,
 1912.0: 5,
 1927.0: 5,
 1933.0: 5,
 1926.0: 5,
 1895.0: 5,
 1896.0: 4,
 1901.0: 4,
 1911.0: 4,
 1925.0: 4,
 1906.0: 4,
 1919.0: 4,
 1907.0: 3,
 1862.0: 3,
 1909.0: 3,
 1878.0: 3,
 1863.0: 3,
 1881.0: 3,
 1902.0: 3,
 1898.0: 3,
 1856.0: 2,
 1904.0: 2,
 1892.0: 2,
 1915.0: 2,
 1923.0: 2,
 1879.0: 2,
 1887.0: 2,
 1877.0: 2,
 1842.0: 2,
 1914.0: 2,
 1883.0: 2,
 1848.0: 1,
 1900.0: 1,
 1903.0: 1,
 1858.0: 1,
 1888.0: 1,
 1828.0: 1,
 1830.0: 1,
 1873.0: 1,
 1913.0: 1,
 1865.0: 1,
 1855.0: 1,
 1852.0: 1,
 1779.0: 1,
 1837.0: 1,
 1875.0: 1,
 1890.0: 1,
 1859.0: 1,
 1864.0: 1,
 1749.0: 1,
 1871.0: 1,
 1839.0: 1,
 1847.0: 1,
 1886.0: 1,
 1703.0: 1,
 1918.0: 1,
 1908.0: 1,
 1868.0: 1,
 1817.0: 1,
 1894.0: 1}

In [85]:
lista = [29, 29, 29, 28, 27, 27, 27, 27, 26, 24, 24, 23, 23, 22, 21, 21, 21, 20, 20, 19, 19, 19, 19, 18, 18, 17, 16, 16, 15, 15, 14, 14, 14, 14, 13, 13, 13, 13, 11, 10, 10, 10, 10, 10, 10, 9, 9, 8, 8, 8, 8, 8, 7, 7, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [91]:
lista=[116, 99, 97, 96, 95, 90, 90, 84, 82, 82, 80, 79, 76, 73, 71, 69, 67, 64, 54, 51, 49, 49, 46, 46, 45, 44, 43, 41, 39, 39, 38, 36, 35, 35, 35, 33, 33, 33, 32, 32]

In [92]:
acumulador=0
import functools 
print (functools.reduce(lambda a,b : a+b,lista))

2398

In [15]:
sattack.to_csv(r'Shark_Attack_Project\shark_attack_cleaned.csv')

In [18]:
sattack.loc[:,'Year'].count()

3464

# Tentando fazer sobre a fatalidade

In [29]:
sattack.loc[:,'Fatal (Y/N)'].value_counts()

N          4293
Y          1388
UNKNOWN      71
 N            7
y             1
2017          1
M             1
N             1
Name: Fatal (Y/N), dtype: int64

In [30]:
sattack['Fatal (Y/N)'].isna().sum()

19960

In [20]:
sattack.replace(' N','N',inplace=True)

In [21]:
sattack.replace('M','N',inplace=True)

In [22]:
sattack.loc[:,'Age']

0             57
1             11
2             48
6             18
7             52
          ...
6243          16
6254          50
6265    13 or 14
6276          16
6301          15
Name: Age, Length: 3465, dtype: object

In [106]:
sattack.drop(columns='Case Number')

In [38]:
sattack.loc[:,'Sex '].value_counts()

M      5094
F       637
N         2
M         2
.         1
lli       1
Name: Sex , dtype: int64

In [113]:
sattacksub.loc[250,'case number']

'2016.07.08'

In [114]:
sattacksub1 = sattacksub

In [ ]:
    '''
        FATAL SHARK BY YEAR
    '''

In [27]:
sattacksub.loc[:,'Fatal (Y/N)'].value_counts()

N          2610
Y           620
UNKNOWN       9
2017          1
Name: Fatal (Y/N), dtype: int64

In [55]:
sattack['Name']=sattack.Name.str.replace('\d+', '')

<ipython-input-55-ce702e109ba1>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  sattack['Name']=sattack.Name.str.replace('\d+', '')

In [54]:
sattack.loc[:,'Name'].str.findall()

TypeError: findall() missing 1 required positional argument: 'pat'

In [ ]:
sattack

In [48]:
sattack = sattack.drop(columns='Unnamed: 23')

In [47]:
sattack = sattack.drop(columns='Unnamed: 22')

In [ ]:
sattack.dropna(axis=0,how='all')

In [49]:
sattack

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN